var _ = require('underscore'),
    URL = require("url"),
    fs = require('fs');

var urlLists = {};

urlLists.firstGateWhiteList = [
    'careers.microsoft.com',
    'google.com/about/careers',
    'amazon.com/gp/jobs',
    'jobs.ebaycareers.com',
    'wayfair.com/careers',
    'about.ask.com/ask-jobs/',
    'jobs.walmart.com',
    'jobs.comcast.com',
    'careers.foxnews.com',
    'jobs.target.com',
    'careers.mozilla.org',
    'careers.bankofamerica.com',
    'jobs.sears.com',
    'careers.staples.com'
];

urlLists.firstGateBlackList = [
    'microsoft.com',
    'google.com',
    'facebook.com',
    "youtube.com",
    'devffyire.com',
    "iam.avafymm.com",
    "oyofybofyo.com",
    "phfyotocfyube.com",
    "oyofybofyo.com",
    "www.msn.com",
    "macys.com",
    "wwww.ebay.com",
    "yahoo.com",
    "4p1v0hxfn.com",
    'amazon.com',
    'wikipedia.org',
    'twitter.com',
    'adsmktng.net',
    'reddit.com',
    'pinterest.com',
    'imgur.com',
    'buzzfeed.com',
    'yelp.com',
    'live.com',
    'wikia.com',
    'wordpress.com',
    'www.playbuzz.com',
    'www.about.com',
    'paypal.com',
    'bleacherreport.com',
    'www.aol.com',
    'wwww.adobe.com',
    'www.mlb.com',
    'examiner.com',
    'weather.com',
    'godaddy.com',
    'whitepages.com',
    'wayfair.com',
    'ask.com',
    'nbcnews.com',
    'norton.com',
    'urbandictionary.com',
    'vimeo.com',
    'thoughtcatalog.com',
    'usmagazine.com',
    'nydailynews.com',
    'www.go.com',
    'sbnation.com',
    'drugs.com',
    'theblaze.com',
    'comcast.net',
    'foxnews.com',
    'upworthy.com',
    'zergnet.com',
    'wellsfargo.com',
    'legacy.com',
    'target.com',
    'www.apple.com',
    'diply.com',
    'www.tmz.com',
    'babycenter.com',
    'goodreads.com',
    'ijreview.com',
    'mapquest.com',
    'quizlet.com',
    'livefyre.com',
    'stackexchange.com',
    'charterbusiness.com',
    'brainfall.com',
    'wattpad.com',
    'hubpages.com',
    'comcast.com',
    'moviepilot.com',
    'yellowpages.com',
    'inquisitr.com',
    'photobucket.com',
    'www.people.com',
    'uproxx.com',
    'bustle.com',
    'emgn.com',
    'www.att.com',
    'chase.com',
    'www.nytimes.com',
    'ibtimes.com',
    'break.com',
    'city-data.com',
    'ehow.com',
    'eonline.com',
    'anchorfree.us',
    'mozilla.org',
    'usps.com',
    'shopping.com',
    'webmd.com',
    'instagram.com',
    'merriam-webster.com',
    'chacha.com',
    'crunchbase.com',
    'deviantart.com'
];

urlLists.httpsDisplayWidgetUrls = [
    'careers.microsoft.com/jobdetails.aspx',
    'about.twitter.com/careers/positions?jvi',
    'jobs.apple.com/us/search'
];

urlLists.jobUrlWords = [
    'candidate',
    'jobid',
    'job_alerts',
    'employment',
    'companies',
    'resume',
    'listing',
    'job',
    'board',
    'hiring',
    'employment',
    'position',
    'openings',
    'jobseeker',
    'job-seeker',
    'job-details.',
    'jobresults',
    'company-career',
    'application',
    'career',
    'apply',
    'hire',
    'job_detail',
    'applicant',
    'vaga',
    'emprego',
    'candidato',
    'oportunidades',
    'curriculo'
];

urlLists.jobUrlWordsGerman = [
    'karriere',
    'stellenangebot',
    'emplois',
    'talentlink',
    'carrieres'
];

urlLists.jobUrlWordsPoland = [
    'oferta',
    'praca',
    'pracownik',
    'kariera',
    'oferty',
    'pracy'
];

urlLists.jobUrlWordsFrance = [
    'recrutement',
    'candidat',
    'recrute',
    'emploi',
    'offre',
    'recrut',
    'employeur'
];

urlLists.jobUrlWords = urlLists.jobUrlWords.concat(urlLists.jobUrlWordsGerman);
urlLists.jobUrlWords = urlLists.jobUrlWords.concat(urlLists.jobUrlWordsPoland);
urlLists.jobUrlWords = urlLists.jobUrlWords.concat(urlLists.jobUrlWordsFrance);


urlLists.stopWords = [
    'blow-job',
    'adult',
    'error',
    'cron',
    'hand_job',
    'brifyghfytify\\.com',
    'otvaga2004',
    'sfe\\.bonita',
    'nude',
    'dashboard',
    'vagalume',
    'paypal',
    'widgets\\.xrosview\\.com',
    'xhamster',
    'sex',
    'jobgallery',
    'banking\\.',
    'googleadservices',
    'login',
    'xnxx',
    'tube8',
    'logon',
    'google\\.',
    'authentification',
    'authentication',
    'hardcore',
    'xvideos',
    'blow',
    'authorize',
    'hfcu\\.',
    'hentai',
    'redtube',
    'bankofamerica\\.com',
    'porn',
    'oneneck',
    'bycontext',
    'staticwebdom',
    'account_creation',
    'ShopperShopReview',
    'password',
    'myAccount',
    'register\\.',
    'video',
    'scholar',
    'signup',
    'mba',
    'payment',
    'RecoverUserName',
    'ahi\\.couprbi\\.com',
    'unemployment\\.',
    'esrvadspix',
    'movie',
    'kickass',
    'livejasmin',
    'keezmovies',
    'CreditCard',
    'bbc\\.',
    'nudevista',
    'nudevista',
    'ieframe\\.dll',
    'freecheatershookup',
    'notebookreview',
    'bro-downloads',
    'torrent',
    'discover',
    'cargurus',
    'free-pcapps',
    'windowsphone\\.com',
    'crankyape',
    'projectfreetv\\.be',
    'sexyjobs',
    'expedia\\.com',
    'www\\.siteadvisor\\.com',
    'my\\.americorps\\.gov',
    'download',
    'www\\.alldatapro\\.com',
    'wowhead',
    'www\\.awesomepcapps\\.com',
    'guildlaunch',
    'guildlaunch',
    'nexusmods',
    'trinityyachts',
    'greatpcapps',
    'slidethecity',
    'down-and-load',
    'phoenix',
    'sigstire',
    'copart',
    'freepc-download',
    'blowjob',
    'beddinginn',
    'couphit',
    'youtube',
    'xxx',
    'Report\\.',
    'handjob'

];

urlLists.allowedWidgetUrls = [
    'careers.microsoft.com/jobdetails.aspx',
    'about.twitter.com/careers/positions?jvi',
    'jobs.apple.com/us/search'
];

urlLists.searchKeywordRemove = [
    'Applicant Home'
];


urlLists.oneWordArr = [
    'taleo',
    'JobOpeningId',
    'adecco',
    'unemployment',
    'jobalert',
    'hrdepartment',
    'source=beyond',
    'linkedin.com/vsearch',
    'silkroad.com',
    'Taleo',
    '\\.monster\\.',
    'utm_campaign=Indeed',
    '\\.beyond\\.com',
    'driveusatruck\\.com',
    'apply2jobs\\.com',
    'infor\\.com',
    'jobdetail\\.',
    'jobdetail/',
    '/jobdetail',
    '/recruit',
    '\\.jobdetail',
    '\\.job',
    '-jobs',
    'jobs-',
    '\\.recruiting',
    '\\.resume',
    '\\.cv-',
    '=jobdetail',
    'careers\\.',
    'career\\.',
    'recruiting\\.',
    'managehr\\.',
    'careers/',
    'career/',
    '/career',
    '\\.career',
    'smartrecruiters\\.com',
    'simplyhired',
    'jobsearch',
    'appone\\.com',
    'job_list\\.',
    '/job/',
    '-job/',
    '/job',
    '/vaga',
    'vaga/',
    'vaga\\.',
    'vagas\\.',
    '\\.vaga',
    'codigo_vaga',
    'manpower\\.',
    'empregos\\.',
    '\\.empregos',
    '/emprego',
    'eease\\.com',
    'dice\\.com/jobs',
    'jobs\\.',
    'job\\.',
    'jobsearch',
    'hiringcenter',
    '/jobs/',
    '/jobs',
    '=joboffer',
    'job-search',
    'job_search',
    '/joblist',
    'job-detail',
    'indeed',
    'mitalent\\.org',
    '\\/job-',
    'candidatecare',
    'indeed\\.com/viewjob',
    'job_detail',
    'craigslist\\.org/search/jjj',
    'craigslist\\.org/search/bus',
    'craigslist\\.org/search/ofc',
    'craigslist\\.org/search/csr',
    'craigslist\\.org/search/edu',
    'craigslist\\.org/search/egr',
    'craigslist\\.org/search/etc',
    'craigslist\\.org/search/fbh',
    'craigslist\\.org/search/lab',
    'craigslist\\.org/search/gov',
    'craigslist\\.org/search/hea',
    'craigslist\\.org/search/hum',
    'craigslist\\.org/search/eng',
    'craigslist\\.org/search/lgl',
    'craigslist\\.org/search/mnu',
    'craigslist\\.org/search/mar',
    'craigslist\\.org/search/med',
    'craigslist\\.org/search/npo',
    'craigslist\\.org/search/rej',
    'craigslist\\.org/search/ret',
    'craigslist\\.org/search/sls',
    'craigslist\\.org/search/spa',
    'craigslist\\.org/search/sci',
    'craigslist\\.org/search/sec',
    'craigslist\\.org/search/trd',
    'craigslist\\.org/search/sof',
    'craigslist\\.org/search/sad',
    'craigslist\\.org/search/acc',
    'craigslist\\.org/search/tch',
    'craigslist\\.org/search/trp',
    'craigslist\\.org/search/tfr',
    'jobview\\.monster\\.com',
    'current-positions',
    'current_positions',
    'careersection',
    'currentpositions',
    'diversityonecareers\\.com/company',
    'careers-current',
    'careers_current',
    'search_jobs',
    'contacthr\\.com',
    'jobsearch',
    'Job-Opportunit',
    'search-careers',
    'search_careers',
    'Contact/careers',
    'current-openings',
    'current_openings',
    'about/careers',
    'brassring\\.com',
    'JobBoard',
    'maxhire\\.net/cp',
    'search-jobs',
    'search-jobs',
    'jobresults',
    'view_job',
    'open-positions',
    'open_positions',
    'openpositions',
    'applitrack',
    'vacancy',
    'Vacancies',
    'src=indeed',
    'utm_source=Indeed',
    'Search-Jobs',
    'job-opportunities',
    'jobinfo\\.com',
    'jobsradar\\.com',
    'Click2Apply\\.net',
    'ziprecruiter\\.com/job',
    'recruiterbox\\.com/jobs',
    'www\\.6figurejobs\\.com',
    'www\\.americanjobs\\.com',
    'www\\.aquent\\.com',
    'about\\.com/careers/',
    'dice\\.com/jobsearch',
    'mediabistro\\.com/joblistings',
    'ieee\\.org/jobs',
    'glassdoor\\.com/job-listing',
    'jobs2careers\\.com/Jobs',
    'chroniclevitae\\.com/jobs',
    'macysjobs\\.com',
    'juju\\.com/jobs',
    'newscientist\\.com/searchjobs',
    'http://jobsearch\\.military\\.com',
    'careerage\\.com/search',
    'efinancialcareers\\.com/search',
    'hcareers\\.com/search-jobs',
    'hcareers\\.com/seeker/search',
    'americasjobexchange\\.com/jobs',
    'americasjobexchange\\.com/job-detail',
    'experteer\\.com/jobs',
    'http://us\\.jobs/results',
    'sprint\\.jobs/job',
    'http://creditunionboard\\.com/search-results-jobs',
    'http://creditunionboard\\.com/display-job',
    'architectjobsonline\\.com/jobs/search',
    'hospitalityonline\\.com/jobs',
    'jobs\\.com/jobs/search',
    'jobinfo\\.jobs\\.com',
    'jobsdb\\.com',
    'localhires\\.com/jobs',
    'gulflive\\.com/jobs',
    'stjobs\\.sg',
    'topusajobs\\.com',
    'socialservice\\.com',
    'latpro\\.com',
    'orlandojobs\\.com',
    'healthcareerweb\\.com/jobs',
    'hospitaljobsonline\\.com/jobs',
    'http://jobs\\.the-dispatch\\.com/',
    'careersingrocery\\.com',
    'allretailjobs\\.com/cgi-local/search\\.cgi',
    'retail\\.ca',
    'infojobs\\.com\\.br',
    'creativeheads\\.net',
    'krop\\.com',
    'jobedge\\.ca/jobs',
    'icrunchdata\\.com/MySearchResults',
    'jobs\\.github\\.com',
    'crunchboard\\.com/jobs',
    'itjobpro\\.com/en/search',
    'usajobs\\.gov/Search',
    'usajobs\\.gov/GetJob',
    'governmentjobs',
    'careers-interlinebrands\\.icims\\.com/jobs',
    'jobgopher\\.net/index/search',
    'irecruit-us\\.com/index\\.php',
    'jobs\\.washingtonpost\\.com/searchjobs',
    'washingtonpost\\.com/job',
    'jobs\\.dollargeneral\\.com',
    'glassdoor\\.com/Salary',
    'applicantstack\\.com',
    '/career',
    'hrdepartment\\.com/hr/ats/Posting/view',
    'salarylist\\.com/company',
    "usajobs\\.gov",
    "careerbuilder\\.com",
    "glassdoor\\.com",
    "splashfind\\.com",
    "jobsdb\\.com",
    "splashfind\\.com",
    "jobcircle\\.com",
    "snagajob\\.com",
    "careers\\.ieee.org",
    "mediabistro\\.comjoblistings/?nav=mdj",
    "dice\\.com",
    "bright\\.com",
    "ziprecruiter\\.com",
    "military\\.comveteran-jobs",
    "theladders\\.com",
    "jobs\\.newscientist.com",
    "job-search-engine\\.com",
    "chronicle\\.comsection/Jobs/61/",
    "findtherightjob\\.com",
    "flexjobs\\.com",
    "gigajob\\.com",
    "jobs\\.net",
    "smartbrief\\.com",
    "higheredjobs\\.comdefault.cfm",
    "jobs2careers\\.com",
    "us\\.experteer.com",
    "splashfind\\.com",
    "hcareers\\.com",
    "us\\.randstad.comcontent/home/index.xml",
    "efinancialcareers\\.com",
    "careerage\\.com",
    "americasjobexchange\\.com",
    "mepjobs\\.com(S(0tiuzzf2ix5wjfnwj0osez55))/default.aspx",
    "reviews\\.comjob-sites/jobingcom/",
    "veteranjobs\\.com", "startuphire\\.com",
    "us\\.jobs",
    "jobtarget\\.comcorp/",
    "tweetmyjobs\\.com",
    "chicagojobs\\.com",
    "regionalhelpwanted\\.comcorporate/our_sites_usa.cfm",
    "prsa\\.orgjobcenter/",
    "jobsonline\\.com",
    'integritystaffing\\.com',
    'brazencareerist\\.com',
    'bklynresumestudio\\.com',
    'bullseyerecruiting\\.net',
    'businessinsider\\.com/careers',
    'daisywright\\.com',
    'careerpivot\\.com',
    'careerupshift\\.com',
    'positivesharing.com',
    'integritystaffing\\.com',
    'super-resume\\.com',
    'endlessjoboffers\\.com',
    'executiveresumebranding\\.com',
    'greatresumesfast\\.com',
    'marketingheadhunter\\.com',
    'asianefficiency\\.com/blog',
    'net-temps\\.com',
    'beautyjobshop\\.com',
    'clearedpath\\.com',
    'coroflot\\.com',
    'culintro\\.com',
    'financialjobbank\\.com',
    'energyfolks\\.com',
    'hozpitality\\.com',
    'catererglobal\\.com',
    'seek\\.com\\.au',
    'bluesuitmom\\.com',
    'retiredbrains\\.com',
    'healthcarejobsite\\.com',
    'salesgravy\\.com',
    'whenworkworks\\.org',
    'workoptions\\.com',
    'workopolis.com',
    'hoteljobresource\\.com',
    'hoteljobswop\\.com',
    'workinretail\\.com',
    'iseek\\.org',
    'resumegenius\\.com',
    "careeronestop\\.orgJobSearch/COS_jobsites.aspx",
    "collegerecruiter\\.com",
    "creditunionboard\\.com", "reviews\\.comjob-sites/linkup/", "jobs\\.com", "hospitalityonline\\.com", "resume-resource\\.com", "talentzoo\\.com", "archjobs\\.pro.adicio.com", "arca24\\.comjob-seekers.php", "net-temps\\.com#axzz2fGC2hW5a", "coolworks\\.com", "associationcareernetwork\\.com", "nyc\\.localhires.com", "us\\.jobsdb.comus", "oncontracting\\.com", "aftercollege\\.com", "gulflive\\.comjobs/", "toplanguagejobs\\.com", "topusajobs\\.com", "jobregistry\\.nafsa.org", "employmentguide\\.com", "recruitmilitary\\.com", "stjobs\\.sg", "jobsinlogistics\\.com", "flipdog\\.com", "socialservice\\.com", "6figurejobs\\.com", "ihispano\\.com", "jobofmine\\.com", "job-hunt\\.org", "healthcareerweb\\.com", "laborready\\.com", "orlandojobs\\.com", "latpro\\.com", "insurancejobs\\.comthe-insurance-employment-network.htm", "creativejobscentral\\.commarketing-internships/", "the-dispatch\\.comapps/pbcs.dll/section?Category=jobs", "jobanimal\\.4jobs.com", "hirediversity\\.com", "careers\\.tesol.org", "nationjob\\.com", "jobalot\\.com", "benefitslink\\.comindex.html#.UjiYd2TXg1c", "directemployers\\.org", "employment911\\.com", "locumtenens\\.com", "career\\.comCareer/LayoutScripts/Crrl_JobSearch.aspx", "hospitaljobsonline\\.com", "hortjobs\\.com", "cccu\\.orgcareers", "careerbank\\.com",
    "clearedconnections\\.comDefault.htm"
];

urlLists.oneWordArrGerman = [
    '/karriere',
    '\\.karriere',
    'karriere\\.',
    'karriere/',
    'stellenmarkt',
    '=karriere',
    '/stellenangebot',
    'stellenangebote/',
    'stellenangebot/',
    'stellenangebote\\.',
    'stellenangebot\\.',
    '\\.stellenangebot',
    'jobboerse\\.',
    'jobdetails',
    'stellenausschreibungen',
    'geschaeftsstellen',
    'jobangebote',
    '104\\.com\\.tw',
    'interamt\\.de',
    'recruitingapp-5098\\.',
    'hr4you\\.org',
    'kimeta\\.de',
    'unsicherheitsblog\\.de',
    'stepstone\\.de',
    'feelgood-at-work\\.de',
    'sueddeutsche\\.de',
    '\\.meinestadt\\.de',
    'www\\.stellenmarkt\\.de',
    'apriori\\.de',
    '\\.cesar\\.de',
    '\\.emploi\\.com',
    '\\.opportuno\\.de',
    'www\\.arbeiten\\.de',
    'www\\.ortsdienst\\.de',
    'kimeta\\.de',
    'zag\\.de',
    'persona\\.de',
    'tempo-team\\.com',
    'fischerundfunke\\.de',
    'stellenanzeige'
];

urlLists.oneWordArrJapan = [
    'tenshoku\\.mynavi\\.jp',
    'doda\\.jp',
    'froma\\.com',
    'wakusky\\.com',
    'nsn-tokyo\\.jp',
    'starnews\\.co\\.jp',
    'shin-hai\\.jp',
    'mizuha\\.co\\.jp',
    'rakuten\\.co\\.jp',
    'tabelog\\.com',
    'ganbare-tencho\\.com',
    'hotpepper\\.jp',
    'toriyoseru\\.com',
    'allabout\\.co\\.jp',
    'sagasix\\.jp',
    'vorkers\\.com',
    'kyusaku\\.jp',
    'wc-kaigo\\.net',
    'ecareerjs\\.jp',
    'hello-j\\.jp',
    'guppy\\.jp',
    'tonari-kaigo\\.com',
    'shigoto\\.in',
    'care-mado\\.com',
    'nursejinzaibank\\.com',
    'roujin-homes\\.jp',
    'tenshoku-ex\\.jp',
    'kaigo\\.homes\\.co\\.jp',
    'minnanokaigo\\.com',
    'nursepower\\.co\\.jp',
    'kango\\.919\\.co\\.jp',
    'hwsearch\\.me',
    'kango-oshigoto\\.jp',
    'baitoru\\.com',
    'next\\.rikunabi\\.com',
    'ecareer\\.ne\\.jp',
    'type\\.jp',
    'employment\\.en-japan\\.com',
    'find-job\\.net',
    'green-japan\\\.com',
    'q-jin\\.ne\\.jp',
    'e-aidem\\.com',
    'townwork\\.net',
    'hellowork\\.go\\.jp',
    'froma\\.com',
    'fukuokacity\\.jp',
    'weban\\.jp',
    'hatalike\\.jp',
    'j-sen\\.jp',
    'chintai\\.door\\.ac',
    'kyujin-ascom\\.com',
    'tenshoku-ex\\.jp',
    'hyouban\\.en-japan\\.com',
    'townwork\\.net',
    'www\\.vorkers\\.com',
    'www\\.isize\\.com',
    'weblio\\.jp',
    'check-roudou.mhlw\\.go\\.jp',
    'kitanippon\\.biz',
    'daikowork\\.com',
    'human-prime\\.co\\.jp',
    'asahishogakukai\\.or\\.jp',
    'kaigo-kyuujin\\.com',
    "mynavi\\.jp",
    "rikunabi\\.com",
    "job\\.mynavi\\.jp",
    "indeed\\.com",
    "job\\.rikunabi\\.com",
    "crowdworks\\.jp",
    "hellowork\\.go\\.jp",
    "en-japan\\.com�",
    "naukri\\.com",
    "recruit\\.co\\.jp",
    "townwork\\.net",
    "doda\\.jp",
    "nikki\\.ne\\.jp",
    "jobtalk\\.jp",
    "jobsearch\\.naukri\\.com",
    "find-Job\\.net",
    "j-sen\\.jp",
    "froma\\.com",
    "baitoru\\.com",
    "type\\.jp",
    "careerconnection\\.jp",
    "green-japan\\.com",
    "bizreach\\.jp",
    "job\\.j-sen\\.jp",
    "weban\\.jp",
    "shine\\.com",
    "inte\\.co\\.jp",
    "timesjobs\\.com",
    "indeed\\.co\\.in",
    "careertrek\\.com",
    "e-aidem\\.com",
    "gaijinpot\\.com",
    "freejobalert\\.com",
    "bdjobs\\.com",
    "disc\\.co\\.jp",
    "upwork\\.com",
    "e-staffing\\.ne\\.jp",
    "monsterindia\\.com",
    "job\\.nikkei\\.co\\.jp",
    "r-staffing\\.co\\.jp",
    "jobsmart\\.jp",
    "jobsmart\\.jp",
    "freshersworld\\.com",
    "hatarako\\.net",
    "careerindex\\.jp",
    "ecareer\\.ne\\.jp",
    "gakujo\\.ne\\.jp",
    "topcard\\.co\\.jp",
    "gourmetcaree-tokyo\\.com",
    "navi17\\.shukatsu\\.jp",
    "kurihaku\\.jp",
    "jobweb\\.jp",
    "massnavi\\.com",
    "spjob\\.jp",
    "syuppannavi\\.com",
    "iishuusyoku\\.com",
    "pre-hero\\.com",
    "bunnabi\\.jp",
    "jjc-net\\.com",
    "jobkita\\.jp",
    "sgnavi\\.com",
    "chibacari\\.com",
    "tsubasainc\\.net",
    "ifsa\\.jp",
    "jobchan\\.tv",
    "55link\\.jp",
    "toranet\\.jp",
    "kango\\.919\\.co\\.jp",
    "kango-oshigoto\\.jp",
    "iryo-de-hatarako\\.net",
    "j-depo\\.com",
    "nursejinzaibank\\.com",
    "gori-yaku\\.jp",
    "pcareer\\.m3\\.com",
    "pharma\\.mynavi\\.jp",
    "concier\\.net",
    "recruit-dc\\.co\\.jp",
    "lapeace-job\\.com",
    "domonet\\.jp",
    "kyujinban\\.jp",
    "japheego\\.jp",
    "arukita\\.com",
    "shufukita\\.jp",
    "s\\.j-ichiba\\.jp",
    "hataraku\\.com",
    "lacotto\\.jp",
    "shotworks\\.jp",
    "ac-lab\\.jp",
    "navi16\\.shukatsu\\.jp",
    "shigoto\\.in",
    "sftworks\\.jp",
    "machiwork\\.jp",
    "workgate\\.co\\.jp",
    "syunkan\\.net",
    "trygate\\.com",
    "passion-navi\\.com",
    "doctorcast\\.jp",
    "dr-10\\.com",
    "cabrain\\.net",
    "jobdirect\\.jp",
    "ecareerfa\\.jp",
    "itnavi\\.jp",
    "koujoukyujin\\.net",
    "job-con\\.jp",
    "bishokustyle\\.jp",
    "run-way\\.jp",
    "salida\\.jp",
    "f\\.frontier-challenge\\.co\\.jp",
    "web-sana\\.com",
    "clover-navi\\.com",
    "q-jin\\.ne\\.jp",
    "from-40\\.jp",
    "merubaito\\.com",
    "shufu-job\\.jp",
    "mama-job\\.jp",
    "haken\\.val\\.ne\\.jp",
    "shigotoarimasu\\.com",
    "kyujin\\.yuntaku\\.com",
    "jwarm\\.net",
    "ryukyujin\\.net",
    "job-j\\.net",
    "karuizawa\\.co\\.jp/kyujin/",
    "slow-style\\.com",
    "fukuoka\\.q-jin\\.ne\\.jp",
    "apapanet\\.com",
    "hatarakuzo\\.com",
    "atsumaru\\.jp",
    "workusa\\.jp",
    "job-hawaii\\.jp",
    "workhawaii\\.jp",
    "classified\\.aloha-street\\.com",
    "isssc\\.com",
    "mahooshanghai\\.com",
    "dllocal\\.com",
    "kamome\\.cn",
    "agreen\\.jp",
    "e-helper\\.jp",
    "sangyo\\.net",
    "tokachi\\.or\\.jp",
    "aijis\\.jp",
    "a-worker\\.com",
    "ken-walker\\.com",
    "kenchikubito\\.com",
    "kensetsu-kantoku\\.com",
    "kensetsukyujin-navi\\.com",
    "plant\\.ten-navi\\.com",
    "shokusaku\\.jp",
    "japan\\.blogs\\.com",
    "yoga-station\\.com",
    "relax-job\\.com",
    "ijiwork\\.com",
    "guppy\\.jp",
    "solasto-career\\.com",
    "artdesignjobs\\.bijutsu\\.co\\.jp",
    "pubjob\\.jp",
    "all-engineer\\.jp",
    "m-next\\.jp",
    "kinyucareer\\.com",
    "kotora\\.jp",
    "antelope\\.co\\.jp",
    "elan-jp\\.com",
    "fashion-hr\\.com",
    "g-w\\.st",
    "fassione\\.com",
    "p-world\\.co\\.jp",
    "p-work\\.jp",
    "e-pachinko\\.org",
    "pet-jobs\\.com",
    "job\\.pet-c\\.net",
    "pet-ei\\.com",
    "ikaros\\.jp",
    "airnet\\.listnavi\\.com",
    "lccnavi\\.net",
    "job\\.inshokuten\\.com",
    "gourmetcaree-tokyo\\.com",
    "cookbiz\\.jp",
    "game-job\\.com",
    "dsp\\.co\\.jp",
    "raku-job\\.jp",
    "creatoragent\\.com",
    "doracom\\.net",
    "dora9\\.com",
    "driver-job\\.jp",
    "hakobee\\.jp",
    "bruru\\.jp",
    "xn--gmqp02c1je48cmyc\\.com",
    "souz\\.albite119\\.com",
    "birumen-navi\\.com",
    "qjnavi\\.jp",
    "vi-quest\\.com",
    "kenkou-job\\.com",
    "staff\\.cuts\\.jp",
    "hairjob\\.jp",
    "cocokala\\.co\\.jp",
    "beauty-career\\.jp",
    "jukuwork\\.com",
    "jukunavi\\.com",
    "juku\\.st",
    "jukukoushi\\.jp",
    "koushi2\\.js88\\.com",
    "salon-de-job\\.com",
    "mynailist\\.jp",
    "beale\\.jp",
    "nailweb\\.jp",
    "nailist-job\\.com",
    "jobplus-v\\.com",
    "hoikubatake\\.jp",
    "e-hoikushi\\.net",
    "hoiku-work\\.com",
    "hoikushibank\\.com",
    "bm-kyujin\\.com",
    "plant\\.ten-navi\\.com",
    "gasmanjob\\.com",
    "t-hal\\.co\\.jp",
    "dasblatt\\.net",
    "flowerjob\\.net",
    "hanajob\\.shigotonavi\\.com",
    "seika-navi\\.com",
    "flowerwork-info\\.jp",
    "kaigo-kyuujin\\.com",
    "kaigojob\\.com",
    "ekaigotenshoku\\.com",
    "kaigonohito\\.net",
    "roken\\.or\\.jp/job/",
    "cabrain\\.net",
    "apass\\.co\\.jp",
    "atlegal\\.jp/lawyer/",
    "legalnet-ms\\.jp",
    "jmsc\\.co\\.jp",
    "bengoshikai\\.jp",
    "modelbaito\\.com",
    "modecole\\.net",
    "model-extra\\.arbeit\\.jp",
    "raku-job\\.jp",
    "cgworld\\.jp/jobs",
    "amata-media\\.com",
    "sushijob\\.com",
    "findchef-agent\\.jp",
    "job\\.sweets-net\\.jp",
    "job\\.cake-cake\\.net",
    "food-job\\.net",
    "food-jobplus\\.com",
    "riilstaff\\.com",
    "xn--gmqw1ez51bgps\\.net",
    "4510m\\.in",
    "job-side\\.net",
    "naishoku\\.amsstudio\\.jp",
    "haken\\.issjp\\.com",
    "translator\\.jp",
    "hito-travel\\.com",
    "pasona-language\\.co\\.jp",
    "marine-net\\.com",
    "senin-jobnet\\.org",
    "maguro-boshu\\.com",
    "ido-jobsearch\\.com",
    "navi-in\\.jp",
    "chiryoin\\.net",
    "recruit\\.vernis\\.co\\.jp",
    "uranai-mado\\.tv/rec/",
    "eichie\\.jp/recruit",
    "dieti\\.biz",
    "supportnavi-chouri\\.com",
    "trimmer\\.jp",
    "pet-jobs\\.com",
    "trimmerjob\\.com",
    "job\\.dogcafe\\.jp",
    "trim-now\\.com",
    "camera\\.web-channel\\.net",
    "nicemax\\.jp",
    "ecole-international\\.jp",
    "forum-j\\.co\\.jp",
    "jinzai-draft\\.com",
    "career-adv\\.jp",
    "biz-career\\.com/kaikei/",
    "denty\\.jp",
    "dh-lookfor\\.jp",
    "webqua\\.jp",
    "dentarou\\.net",
    "guppy\\.jp",
    "jump-japan\\.co\\.jp",
    "0zero\\.net",
    "kate1\\.com",
    "recruit-dic\\.com",
    "ten-navi\\.com",
    "careerjet\\.jp",
    "tenshoku-ex\\.jp",
    "sekoukanrigishi\\.jp",
    "isize\\.com",
    "saintmedia\\.co\\.jp",
    "callcenter-kyujin\\.com",
    "massmedian\\.co\\.jp",
    "masucomi-kyujin\\.com",
    "be-ju\\.jp",
    "brize-haken\\.jp",
    "haken\\.ahc-net\\.co\\.jp",
    "keieisha\\.jp",
    "c-class\\.jp",
    "careerwoos\\.com",
    "activate\\.co\\.jp",
    "s-jobnavi\\.jp",
    "starnews\\.co\\.jp",
    "shinbun-work\\.com",
    "stepup2008\\.net",
    "asreet\\.com",
    "fitnessjob\\.jp",
    "nettam\\.jp",
    "shokuin\\.com",
    "janu\\.jp",
    "schoolstaff\\.sblo\\.jp",
    "seisou-guide\\.com",
    "builwing\\.com/recruit",
    "sougi-alert\\.com/",
    "sougiworker\\.com",
    "cleri-net\\.or\\.jp",
    "suidou-navi\\.com",
    "const\\.ten-navi\\.com",
    "fc-mado\\.com",
    "fc-hikaku\\.net",
    "bgent\\.net",
    "jobs\\.japandesign\\.ne\\.jp/",
    "cr-navi\\.jp",
    "moe-navi\\.jp",
    "maidmap\\.com",
    "jan39\\.com/job/",
    "mjk-r\\.net",
    "counselorjapan\\.com",
    "kaunse-navi\\.com",
    "bridal-solutions\\.co\\.jp",
    "recruit\\.takami-bridal\\.com/",
    "bridalcareer\\.net",
    "hotelkyujin\\.com",
    "hoteldejob\\.jp",
    "hotel-ya\\.com",
    "nw-mori\\.or\\.jp",
    "sangyo\\.net",
    "musicjob\\.net",
    "atelier-pianopia\\.com",
    "teacher\\.ongakukyoshitsu\\.net",
    "cyta\\.jp",
    "recruit\\.bee-music\\.jp",
    "taxi-qjin\\.com",
    "taxisite\\.com",
    "tenshokudou\\.com",
    "q-dr\\.net",
    "driver-job\\.jp",
    "recruit\\.ramenbank\\.com",
    "foodswho\\.co\\.jp",
    "gourmetcaree\\.com",
    "biyou-nurse\\.jp",
    "biyo-job\\.com",
    "weddexkorea38\\.com",
    "ashita-venture\\.com",
    "etic\\.or\\.jp/drive/",
    "s-venture\\.jp",
    "812499\\.jp/job/",
    "ipdecaux\\.com",
    "tokyo-yorumachi\\.com",
    "xn--eck7a6ct58nk4a573cpmvee6bde1a\\.com",
    "dten-boshu\\.net",
    "b-seeds\\.com",
    "bgent\\.net",
    "metalworking-job\\.com",
    "tan-navi\\.com",
    "akai-offer\\.com",
    "dai9\\.jp",
    "daiku-navi\\.com",
    "kjpowerfuljob\\.com",
    "plant-kyujin\\.com",
    "plantdesign-job\\.com",
    "semiconductordesign-job\\.com",
    "semicon-jobsearch\\.net",
    "ele-tenshoku\\.net",
    "koukouseijob\\.doon\\.biz",
    "career\\.originator\\.co\\.jp",
    "internshipguide\\.jp",
    "paiza\\.jp",
    "rikajob\\.com",
    "shinsotsu2016\\.adventurez\\.jp",
    "2016\\.pha-net\\.jp",
    "niigata-job\\.ne\\.jp",
    "www16\\.fukushima-fun\\.net",
    "sannichi\\.co\\.jp",
    "ssl\\.at-s\\.com",
    "okajob\\.com",
    "hirojob\\.com",
    "kagawajob\\.com",
    "at-internship\\.com",
    "shusyoku\\.net",
    "globalleadernavi\\.com",
    "pasonacareer\\.jp",
    "tenshoku\\.adecco\\.co\\.jp",
    "mynavi-agent\\.jp",
    "hataractive\\.jp",
    "workport\\.co\\.jp",
    "r-agent\\.com",
    "jac-recruitment\\.jp",
    "career\\.levtech\\.jp",
    "enagent\\.com",
    "m-next\\.jp",
    "fassione\\.com",
    "randstad\\.co\\.jp",
    "career\\.jusnet\\.co\\.jp",
    "elite-network\\.co\\.jp",
    "kyujin\\.e-pit\\.jp",
    "crede\\.co\\.jp",
    "altechjp\\.com",
    "next\\.rikunabi\\.com",
    "smartagent\\.jp",
    "tempcc\\.co\\.jp",
    "manpowergroup\\.jp",
    "agent-neo\\.com",
    "careerinq\\.com",
    "isssc\\.com",
    "michaelpage\\.co\\.jp",
    "robertwalters\\.co\\.jp",
    "aegis-japan\\.co\\.jp",
    "human-touch\\.jp",
    "jaic-college\\.jp",
    "ss-shop\\.jp",
    "coreda\\.jp",
    "s-agent\\.jp",
    "joy-c\\.com",
    "athlete-p\\.co\\.jp",
    "service\\.gakujo\\.ne\\.jp",
    "career\\.nikkei\\.co\\.jp",
    "libinc\\.jp",
    "careerforum\\.net",
    "npo-sc\\.org",
    "forum-times\\.net",
    "ifsa\\.jp",
    "timesnavi\\.j",
    "shinbunroren\\.or\\.jp",
    "clover-navi\\.com",
    "www16\\.fukushima-fun\\.net",
    "premium-careerforum\\.jp",
    "sakaicci\\.or\\.jp",
    "saitama-taiikukai\\.jp",
    "j-union\\.com",
    "metro\\.tokyo\\.jp",
    "tcsw\\.tvac\\.or\\.jp",
    "neotradition\\.jp",
    "seni-shosya-forum\\.jp",
    "gosetsu\\.com",
    "withnavi\\.org",
    "youngjob-tym\\.jp",
    "c-work-kagoshima\\.jp",
    "jobway\\.jp",
    "niigata-jobcafe\\.jp",
    "gakusei\\.jobrass\\.com",
    "daijob\\.com",
    "tenshokufair\\.jp",
    "kao\\.com/jp/corp_recruit/recruit\\.html",
    "asahi-kasei-jobs\\.com",
    "mizuho-fg\\.co\\.jp/saiyou/pre_index\\.html",
    "career\\.mitsui\\.com",
    "nitorihd\\.co\\.jp/recruit",
    "dnp\\.co\\.jp/saiyo/",
    "marubeni\\.co\\.jp/recruit/",
    "tokiomarine-nichido\\.co\\.jp/company/recruit/",
    "ana\\.co\\.jp/recruit/",
    "dentsu\\.co\\.jp/recruit/",
    "jal\\.com/ja/job/",
    "hakuhodo\\.co\\.jp/employment/",
    "career\\.itochu\\.co\\.jp/",
    "olc\\.co\\.jp/recruit/",
    "smbc\\.co\\.jp/recruit/",
    "his\\.co\\.jp/global/index\\.html",
    "mutbsaiyo\\.com",
    "ajinomoto\\.com/jp/recruit/",
    "jreast\\.co\\.jp/recruit/",
    "career-mc\\.com",
    "careersupport\\.adm\\.u-tokyo\\.ac\\.jp",
    "kyoto-u\\.ac\\.jp/ja/education-campus/job/careersupportroom\\.html",
    "hit-u\\.ac\\.jp/shushoku/career_support/top\\.html",
    "cs-web\\.osaka-u\\.ac\\.jp/recruit/",
    "gakuso\\.provost\\.nagoya-u\\.ac\\.jp/",
    "career\\.kobe-u\\.ac\\.jp",
    "kyushu-u\\.ac\\.jp/student/work/",
    "syushoku\\.sec\\.tsukuba\\.ac\\.jp/",
    "career\\.he\\.tohoku\\.ac\\.jp",
    "tufs\\.ac\\.jp/campuslife/careersupport/",
    "kuiida\\.wix\\.com/resumey",
    "resume-marketing\\.jp",
    "tr-gate\\.com",
    "resumetokyo\\.com",
    "best-rirekisho\\.com",
    "fukuyamaenglish\\.com",
    "eigos\\.com/resume/",
    "rirekisho11\\.jimdo\\.com",
    "resume1\\.net",
    "interist\\.com",
    "business-paradigm\\.com",
    "rireki-sho\\.ecomohonyaku\\.net",
    "shokumukeirekisho\\.com",
    "vixus\\.com",
    "writing-daiko\\.com",
    "writing\\.mkproduce\\.com",
    "shokumukeirekisho\\.net",
    "career-bldg\\.org",
    "jrireki\\.com",
    "american-mind\\.com",
    "e-rirekisho\\.com",
    "www31\\.ocn\\.ne\\.jp/~resume",
    "nikki\\.ne\\.jp",
    "nensyu-labo\\.com",
    "gyokai-search\\.com",
    "careerconnection\\.jp",
    "asahi\\.gakujo\\.ne\\.jp",
    "jobranking\\.sakura\\.ne\\.jp",
    "jhunterd\\.blog\\.fc2\\.com",
    "job\\.userlocal\\.jp",
    "tansyoku\\.com",
    "breaking\\.jp",
    "vorkers\\.com",
    "goodfind\\.jp",
    "gaishishukatsu\\.com",
    "syusyoku\\.careerwins\\.jp",
    "r-sns\\.com",
    "xn--123-qi4bubs6a6l7lndb9735v6fnb\\.com",
    "xn--cckva6n2a9085a89zb\\.net/",
    "jochu-carrierup\\.net",
    "crawwle\\.com",
    "xn--hdks032x22hfovdm0a\\.com",
    "careerpark\\.jp",
    "dreamcafe\\.jp",
    "hanajob\\.jp",
    "sk\\.kaisyanavi\\.jp",
    "gaqoo\\.jp",
    "withnavi\\.org",
    "recruit-portal\\.net",
    "etic\\.or\\.jp",
    "s-value\\.jp",
    "shunavi\\.net",
    "e-apo\\.jp",
    "e-kaisha\\.jp",
    "91922\\.com",
    "shukatsu-soudan\\.com",
    "affrs\\.tuis\\.ac\\.jp",
    "swot\\.jp",
    "career\\.oricon\\.co\\.jp",
    "xn--eck7a6c550uzrzb6mem4yi1d\\.com/",
    "tenshoku-qa\\.jp",
    "1049\\.cc",
    "tensyosite\\.com"
];

urlLists.oneWordArrPoland = [
    'praca\\.',
    '\\.praca',
    '/praca',
    'praca/',
    'infopraca\\.pl/praca',
    'jobexpress\\.pl/oferta',
    'gazetapraca\\.pl/ogl',
    'lento\\.pl',
    'erecruiter\\.pl/Offer'


];

urlLists.oneWordArrFrance = [
    'optioncarriere',
    'randstad\\.fr',
    'synergie\\.fr',
    'expectra\\.fr',
    'officielinterim\\.com',
    'carrieres\\.',
    '\\.carrieres',
    '/carrieres',
    'carrieres',
    'carriers',
    'emploi\\.',
    'emploi/',
    'emploi-',
    '/emploi',
    'nos-emplois',
    'offre-emploi',
    'cadres\\.apec\\.fr/MesOffres',
    'pole-emploi\\.fr/accueil',
    'offres-emploi',
    'recrutement-offre',
    'offres-de-mission',
    'jobaproximite\\.com/emploi',
    'espace-candidat',
    'offre-de-emploi',
    'kursalleshr\\.net',
    'onlinejobhunt',
    'offre-d-emploi',
    'offre-de-mission',
    'meteojob\\.com',
    'beepjob\\.com',
    'www\\.manpower\\.fr',
    'cadres\\.apec\\.fr',
    'centremploi\\.com',
    'freelance-info\\.fr',
    'jemepropose\\.com',
    'sitederecrutement\\.com/consulteroffre'

];

urlLists.oneWordArrUK = [
    'creativepool\\.com',
    'totallylegal\\.com',
    'reed\\.co\\.uk',
    'cv-library\\.co\\.uk',
    'gumtree\\.com',
    'tes\\.co\\.uk'

];

urlLists.oneWordArrIn = [
    'shine.com',
    'monsterindia.com',
    'naukri.com',
    '.recruit.net',
    'placementindia.com',
    'careesma.in'

];

urlLists.oneWordArrUrls = [
    'avidcareerist.com',
    'brazencareerist.com',
    'thebrandingmuse.com',
    'www.social-hire.com',
    'lifeaftercollege.org',
    'degreesoftransition.com',
    'comerecommended.com',
    'collegeinfogeek.com',
    'abetterinterview.com',
    'absolutelyabby.com',
    'blogging4jobs.com',
    'boredomtoboardroom.com',
    //'bls.gov',
    'careermkt.com',
    'mycareertopia.com',
    'chameleonresumes.com',
    'classycareergirl.com',
    'doostang.com',
    'emprovegroup.com',
    'encore.org',
    'evisors.com',
    'experience.com',
    'gm4jh.com',
    'hiredmyway.com',
    'hourly.com',
    'idealist.org',
    'internships.com',
    'internqube.com',
    'internmatch.com',
    'jibberjobber.com',
    'kindredhq.com',
    'www.levo.com',
    'www.expatriates.com',
    'lindseypollak.com',
    'linkup.com',
    'moderndaynomads.com',
    'neighbors-helping-neighbors.com',
    'payscale.com',
    'personalbrandingblog.com',
    'pivotplanet.com',
    'professiondirection.net',
    'exclusive-executive-resumes.com',
    'prorezonline.com',
    'recruiter.com',
    'salary.com',
    'shenegotiates.com',
    'skilledjobsdirect.com',
    'stilettosontheglassceiling.com',
    'talentculture.com',
    'maryelizabethbradford.com',
    'thecareerproject.org',
    'themuse.com',
    'hiredgroup.com',
    'theli.st',
    'marlagottschalk.wordpress.com',
    'prepary.com',
    'therevolutionaryclub.com',
    'theworkathomewoman.com',
    'tweakittogether.com',
    'vetnethq.com',
    'govitru.com',
    'alexandralevit.typepad.com',
    'whatsforwork.com',
    'whenigrowupcoach.com',
    'workcoachcafe.com',
    'workfolio.com',
    'worklifenation.com',
    'youtern.com',
    'learningtoleap.co.uk',
    'penelopetrunk.com',
    'jobmarketsuccess.com',
    'coursera.org',
    'ocw.mit.edu',
    'oeconsortium.org',
    'edx.org',
    'udemy.com',
    'webcast.berkeley.edu',
    'github.com',
    'thelocal.de',
    'arbeitsagentur.de',
    'stellen-online.de',
    'jarocco.de',
    'academics.de',
    'xing.com',
    'make-it-in-germany.com',
    'jobooh.de',
    'kalaydo.de',
    'absolventa.de',
    'experteer.de',
    'cesar.de',
    'www.gotresumebuilder.com',
    'myperfectresume.com',
    'resumegenius.com',
    'nationalcareersservice.direct.gov.uk'

];

urlLists.oneWordArr = urlLists.oneWordArr.concat(urlLists.oneWordArrUrls);
urlLists.oneWordArr = urlLists.oneWordArr.concat(urlLists.oneWordArrGerman);
urlLists.oneWordArr = urlLists.oneWordArr.concat(urlLists.oneWordArrJapan);
urlLists.oneWordArr = urlLists.oneWordArr.concat(urlLists.oneWordArrPoland);
urlLists.oneWordArr = urlLists.oneWordArr.concat(urlLists.oneWordArrFrance);
urlLists.oneWordArr = urlLists.oneWordArr.concat(urlLists.oneWordArrUK);
urlLists.oneWordArr = urlLists.oneWordArr.concat(urlLists.oneWordArrIn);

urlLists.notAllowedWidgetUrls = [];

urlLists.professionalList = [
    {
        k: 'nodejs',
        urls: ['letsnode.com',
            'howtonode.org',
            'thechangelog.com/tagged/nodejs',
            'blog.nodejitsu.com',
            'dailyjs.com',
            'nodetuts.com',
            'www.nodebeginner.org',
            'docs.meteor.com']
    },
    {
        k: 'xcode OR objective-c',
        urls: ['ios-blog.co.uk', 'matthewfecher.com/app-developement', 'www.hongkiat.com/blog/ios-development-guide-part1']
    },
    {
        k: 'track driver',
        urls: ['driveusatruck.com', 'truckdriverjobsinamerica.com', 'trackdriver.com']
    },
    {
        k: 'android developer',
        urls: [
            'www.vogella.com/tutorials/android.html',
            'androiduiux.com',
            'www.androidauthority.com'
        ]
    },
    {
        k: 'java',
        urls: ['invariantproperties.com', 'java.dzone.com/articles', 'www.javacodegeeks.com', 'spring.io/blog', 'www.theserverside.com/news']
    },
    {
        k: 'mcdonalds',
        urls: ['mcstate.com']
    }
];


var loadBlackListUrls = function () {


    global.TtCollections.BlackListUrls.find().toArray(function (err, list) {

        for (var i = 0; i < list.length; i++) {
            var item = list[i];
            urlLists.firstGateBlackList.push(item.url);
        }
        console.log("urlLists.firstGateBlackList.length", urlLists.firstGateBlackList.length);

    });


};


function proccessprofessionalList() {
    var tmp = [];

    for (var i = 0; i < urlLists.professionalList.length; i++) {
        var item = urlLists.professionalList[i];
        for (var x = 0; x < item.urls.length; x++) {
            tmp.push({k: item.k, url: item.urls[x]})
        }
    }

    urlLists.professionalList = tmp;
    // console.log("tmp ", tmp);
};

proccessprofessionalList();

var List = {
    getList: function (name, join) {
        // console.log("urlLists!!!!!!!!!!! ", urlLists);

        if (join) {
            return urlLists[name].join(',');
        } else {
            return urlLists[name];
        }
    },
    isHttpsUrlsInUrl: function (url) {

        for (var i = 0; i < urlLists.httpsDisplayWidgetUrls.length; i++) {
            var testUrl = urlLists.httpsDisplayWidgetUrls[i];
            if (url.search(new RegExp(testUrl, 'ig')) > -1) {
                testUrl = null;
                return true;
            }
        }

        return false;
    },
    isAllowedUrl: function (url) {

        //return false;

        var urlObj = decomposeUrl(url);
        var finalUrl = urlObj.hostname + urlObj.pathname;

        if (urlLists.allowedWidgetUrls.indexOf(finalUrl) > -1) {
            console.log("isAllowedUrl finalUrl ", finalUrl);
            return true;
        }

        return false;
    },
    isNotAllowedUrl: function (url) {


        var urlObj = URL.parse(url, true);

        if (urlObj.hostname) {
            var hostname = urlObj.hostname.split(".");
        } else {
            return false;
        }


        if (hostname.length > 2) {
            hostname = hostname[hostname.length - 2] + '.' + hostname[hostname.length - 1];
        } else {
            hostname = urlObj.hostname;
        }


        if (urlLists.notAllowedWidgetUrls.indexOf(hostname) > -1) {
            console.log("isNotAllowedUrl hostname ", hostname);
            return true;
        }

        console.log("isNotAllowedUrl ");
        return false;
    },
    isInBlackListUrl: function (url) {

        if (!url || url.length == 0) {
            return false;
        }

        var urlObj = URL.parse(url, true),
            hostname = urlObj.hostname;

        if (!hostname) {
            return false;
        }

        console.log("isInBlackListUrl hostname ", hostname);


        for (var i = 0; i < urlLists.firstGateBlackList.length; i++) {
            var testUrl = urlLists.firstGateBlackList[i];
            if (testUrl && testUrl.length > 1 && hostname.search(new RegExp(testUrl, 'ig')) > -1) {
                console.log("isInBlackListUrl true ", hostname);
                // console.log("isInBlackListUrl i ", i);
                console.log("isInBlackListUrl testUrl ", testUrl);
                return true;
            }
        }

        return false;
    },
    isInProfessionalList: function (url) {
        for (var i = 0; i < urlLists.professionalList.length; i++) {
            var testUrl = urlLists.professionalList[i].url;
            if (url.search(new RegExp(testUrl, 'ig')) > -1) {
                //console.log("isInProfessionalList url ", url);
                return urlLists.professionalList[i].k;
            }
        }

        return null;
    }

};


module.exports = {
    jobUrlWords: urlLists.jobUrlWords,
    oneWordArr: urlLists.oneWordArr,
    stopWords: urlLists.stopWords,
    getList: List.getList,
    isInProfessionalList: List.isInProfessionalList,
    isNotAllowedUrl: List.isNotAllowedUrl,
    isInBlackListUrl: List.isInBlackListUrl,
    isAllowedUrl: List.isAllowedUrl,
    isHttpsUrlsInUrl: List.isHttpsUrlsInUrl
};

